In [ ]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import time
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
import warnings

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
filepath = "/content/gdrive/MyDrive/iot_23_data/iot23_combined (2).csv"

In [ ]:
df = pd.read_csv(filepath)

In [ ]:
del df['Unnamed: 0']

In [ ]:
df

         duration  orig_bytes  ...  conn_state_SH  conn_state_SHR
0        2.998796           0  ...              0               0
1        0.000000           0  ...              0               0
2        0.000000           0  ...              0               0
3        2.998804           0  ...              0               0
4        0.000000           0  ...              0               0
...           ...         ...  ...            ...             ...
1521502  0.000000           0  ...              0               0
1521503  0.000000           0  ...              0               0
1521504  0.000000           0  ...              0               0
1521505  0.000000           0  ...              0               0
1521506  0.000000           0  ...              0               0

[1521507 rows x 25 columns]

In [ ]:
df['label'].value_counts()

8    880860
7    262690
0    240842
5    124362
1      8437
9      3915
2       357
4        30
6        13
3         1
Name: label, dtype: int64

In [ ]:
DT = DecisionTreeClassifier()

In [ ]:
X = df[['duration', 'orig_bytes', 'resp_bytes', 'missed_bytes', 'orig_pkts', 'orig_ip_bytes', 'resp_pkts', 'resp_ip_bytes', 'proto_icmp', 'proto_tcp', 'proto_udp', 'conn_state_OTH', 'conn_state_REJ', 'conn_state_RSTO', 'conn_state_RSTOS0', 'conn_state_RSTR', 'conn_state_RSTRH', 'conn_state_S0', 'conn_state_S1', 'conn_state_S2', 'conn_state_S3', 'conn_state_SF', 'conn_state_SH', 'conn_state_SHR']]
Y = df['label']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=10, test_size=0.2)

In [ ]:
start = time.time()
print('program start...')
print()

DT.fit(X_train, Y_train)
print()

print('prediction:')
y_pred = DT.predict(X_test)
print(y_pred)
print()

print('Score:')
score = DT.score(X_test,Y_test)
print(score)

end = time.time()
print('program end...')
print()
print('time cost: ')
print(end - start, 'seconds')

program start...


prediction:
[5 8 8 ... 8 5 8]

Score:
0.7441883392156476
program end...

time cost:
3.383216142654419 seconds

In [ ]:
warnings.filterwarnings('ignore')

In [ ]:
print("Classifiction Report :")
print(classification_report(Y_test, y_pred))

Classifiction Report :
              precision    recall  f1-score   support

           0       0.98      0.62      0.76     48008
           1       0.28      0.02      0.03      1779
           2       0.94      0.38      0.54        76
           3       0.00      0.00      0.00         0
           4       0.50      0.12      0.20         8
           5       1.00      0.80      0.89     25072
           6       0.00      0.00      0.00         0
           7       0.71      0.00      0.00     52611
           8       0.69      1.00      0.82    175952
           9       1.00      0.99      0.99       796

    accuracy                           0.74    304302
   macro avg       0.61      0.39      0.42    304302
weighted avg       0.77      0.74      0.67    304302